"""Configuration for autogenerated tests to handle heavy dependencies."""
import sys
from unittest.mock import MagicMock

# Pre-mock heavy dependencies before any test imports
def pytest_configure(config):
    """Configure mocks for autogenerated tests."""
    # Mock websockets and its submodules
    websockets_mock = MagicMock()
    websockets_mock.exceptions = MagicMock()
    sys.modules["websockets"] = websockets_mock
    sys.modules["websockets.exceptions"] = websockets_mock.exceptions
    
    # Mock other heavy dependencies
    sys.modules["pandas"] = MagicMock()
    sys.modules["numpy"] = MagicMock()
    sys.modules["google.cloud.storage"] = MagicMock()
    sys.modules["gymnasium"] = MagicMock()
    sys.modules["torch"] = MagicMock()
    sys.modules["optuna"] = MagicMock()
    sys.modules["scipy"] = MagicMock()
    sys.modules["scipy.stats"] = MagicMock()