# Project Configuration for BTC/USDT Ï„-SAC Trading System

# Google Cloud Platform Settings
gcp:
  project_id: "my-project-779482"
  region: "asia-northeast3"  # Seoul
  zone: "asia-northeast3-a"
  
  # Storage Configuration
  storage:
    bucket_name: "btc-orderbook-data"
    raw_data_prefix: "raw/"
    processed_data_prefix: "processed/"
    features_data_prefix: "features/"
    
  # Vertex AI Configuration
  vertex_ai:
    staging_bucket: "btc-model-staging"
    model_registry: "btc-tau-sac-models"
    endpoint_region: "asia-northeast3"
    machine_type: "n1-standard-8"
    accelerator_type: "NVIDIA_TESLA_T4"
    accelerator_count: 1

# CI/CD Configuration
ci:
  python_version: "3.10"
  test_coverage_threshold: 80
  max_line_length: 100
  
# Repository Information
repository:
  owner: "unsuperior-ai"
  name: "lisa-btc-trade-pipeline"
  main_branch: "main"
  develop_branch: "develop"