name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.10'
  GCP_PROJECT_ID: 'my-project-779482'
  GCS_BUCKET: 'btc-orderbook-data'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-minimal.txt
    
    - name: Run type checking
      run: mypy --install-types --non-interactive --ignore-missing-imports src tests
    
    - name: Run linting
      run: |
        ruff check src tests
        black --check src tests
    
    - name: Run security checks
      run: |
        bandit -r src tests -ll
    
    - name: Run tests with coverage
      run: pytest tests/ --cov=src --cov-report=xml --cov-report=term-missing -v
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  gcp-validation:
    runs-on: ubuntu-latest
    needs: test
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
    
    - name: Test GCP Authentication
      run: |
        echo "Testing GCP authentication..."
        gcloud auth list
        gcloud config list
    
    - name: Validate GCS permissions
      run: |
        echo "Validating GCS bucket access..."
        gsutil ls gs://${{ env.GCS_BUCKET }}/ || echo "GCS access failed"
    
    - name: Test GCS Upload
      run: |
        echo "Testing GCS upload..."
        echo "Test file from CI - $(date)" > test-ci.txt
        gsutil cp test-ci.txt gs://${{ env.GCS_BUCKET }}/ci-test/test-ci-$(date +%Y%m%d-%H%M%S).txt || echo "Upload failed"
        rm -f test-ci.txt
    
    - name: Validate Vertex AI pipeline
      run: |
        # Validate pipeline YAML syntax
        python -c "import yaml; yaml.safe_load(open('btc_preprocess_pipeline.yaml'))"

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: |
        docker build -t btc-trading-system:test .
    
    - name: Run Docker security scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'btc-trading-system:test'
        exit-code: '0'
        severity: 'CRITICAL,HIGH'